### ISSUE TITLE
Dependency Not Found

### ISSUE THREAD

**Issue by robert-moore** [wa0x6e/cal-heatmap#335]
`yarn add cal-heatmap`

**package.json updates**

```
...
"dependencies": {
  ...,
  "cal-heatmap": "^4.1.0",
  ...
},
...
```

**Definitely in node_modules:**

![image](https://user-images.githubusercontent.com/4934366/225748137-1113dfed-0140-4182-81d1-278f7e25305c.png)

**TS File**

```
import CalHeatmap from 'cal-heatmap';
```

**Get error:**

`This dependency was not found:

* cal-heatmap in ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/SubscriptionAnalytics/CustomerActivity.vue?vue&type=script&lang=ts&

To install it, you can run: npm install --save cal-heatmap`

**Comment by wa0x6e** [comment]
Are you importing it in a VueJS project ?

**Comment by robert-moore** [comment]
Yes I am

**Comment by wa0x6e** [comment]
I just tried importing cal-heatmap inside a newly created vuejs app, and it does work. There is now a repo for a starter vuejs app integrating cal-heatmap:

https://github.com/wa0x6e/cal-heatmap-vue-starter 

I guess the issue is somewhere else, like in https://github.com/wa0x6e/cal-heatmap/issues/332 ?
