### ISSUE TITLE
Legend colors/values not working properly

### ISSUE THREAD

**Issue by joshuamckay** [wa0x6e/cal-heatmap#90]
I appear to have an issue where data values of 1 are sometimes colored properly, and sometimes colored as "less than 1" per the legend.  See attached image with a tooltip for the day, the first legend entry, and the second legend entry.  This is the legend code I'm using:

 <code>legend: [1,4,8,12,20]}</code>

Not sure why days with a value of 1 are randomly showing gray.

![legend](https://cloud.githubusercontent.com/assets/4750853/3306856/c6096200-f665-11e3-87e9-2972e66e1bff.png)

**Comment by JoshKeegan** [comment]
I'm having the same problem.

Agree with @jamesburke-examtime that it looks like it's the legend title text that is wrong, with less than actually being less than or equal to etc... This (<=) is actually the behaviour I want (although perhaps it should be optional?), so it's just the title text that's wrong from my perspective.

Another thing with the legend is that if you're only using integers and have the legend set to single values (so [1, 2, 3, 4, 5]) then it'd be good to have the option to just show the actual numbers in the key, rather than "Less than 1", "Less than 2" etc...

**Comment by dokgu** [comment]
Having this same issue. I think you can fix this by treating the legend values as the upper bound (inclusive).

So let's say a setting of `[10, 20, 30, 40]` would be interpreted as:

**Legend 1:** `<= 10`
**Legend 2:** `11-20`
**Legend 3:** `21-30`
**Legend 4:** `31-40`
**Legend 5:** `>= 40`

I would personally include: **Legend 0:** `empty` - but that's for another discussion.

**Comment by wa0x6e** [comment]
Comment above is right, the legend array values are threshold

Next v4 legend is rewritten from the ground up, and will allow more flexibility
